inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - '**/spec/**/*'
    - 'pakyow-mailer/**/*'
    - 'pakyow-presenter/**/*'
    - 'pakyow-rake/**/*'
    - 'pakyow-realtime/**/*'
    - 'pakyow-support/**/*'
    - 'pakyow-test/**/*'
    - 'pakyow-ui/**/*'
  DisplayCopNames: true

BlockDelimiters:
  EnforcedStyle: semantic

Lint/AssignmentInCondition:
  Enabled: false

Metrics:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
