language: ruby
sudo: required
dist: xenial

services:
  - redis-server
  - mysql

addons:
  postgresql: 10

rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head

env:
  matrix:
    - CI=true
    - CI_BENCH=true
    - CI_SMOKE=true

matrix:
  include:
    - language: ruby
      before_install:
        - gem install bundler
      script:
        - bundle exec rake

    - language: node_js
      node_js:
        - node
      before_install:
        - cd pakyow-js
      script:
        - npm test

  exclude:
    - rvm: 2.4.4
      env: CI_BENCH=true
    - rvm: ruby-head
      env: CI_BENCH=true
    - rvm: ruby-head
      env: CI_SMOKE=true

  allow_failures:
    - rvm: ruby-head
    - env: CI_BENCH=true

  fast_finish: true

notifications:
  email: false
