matrix:
  include:
    - sudo: false
      language: ruby
      rvm:
        - 2.4.0
        - 2.4.1
        - 2.4.2
        - 2.5.0
        - 2.5.1
        - 2.6.0-preview1
      script: "bundle exec rake"
      before_install: gem install bundler
      services:
        - redis-server
      before_script:
        - psql -c "CREATE DATABASE travis;" -U postgres

    - language: node_js
      node_js:
        - node
      script: npm test
      before_install: cd pakyow-js-source

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9d2966f0802fa60b226f
