matrix:
  include:
    - sudo: false
      language: ruby
      rvm:
        - 2.4.0
        - 2.4.1
        - 2.4.2
        - 2.5.0
        - 2.5.1
        - 2.6.0-preview1
      script: "bundle exec rake"
      before_install: gem install bundler
      addons:
          code_climate:
              repo_token: 5cbfd85e621316c736d7bb2ae9e1dc93689e0321095f21dfc2cf23a5335d71a1
      services:
        - redis-server
      before_script:
        - psql -c "CREATE DATABASE travis;" -U postgres

    - language: node_js
      node_js:
        - node
      script: npm test
      before_install: cd pakyow-js

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9d2966f0802fa60b226f
